apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - part-db-helm.yaml
secretGenerator:
  - name: db-connection
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml