---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: part-db
  namespace: flux-system
spec:
  interval: 10m
  url: https://part-db.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: part-db
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: part-db
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: part-db
        namespace: flux-system
      # valuesFiles:
      #   - values.yaml
  targetNamespace: part-db
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: db-connection
