apiVersion: v1
kind: Service
metadata:
  name: zenoh-router
  labels:
    app: zenoh-router
spec:
  selector:
    app: zenoh-router
  ports:
  - name: tcp-7447
    protocol: TCP
    port: 7447
    targetPort: 7447
  - name: udp-7446
    protocol: UDP
    port: 7446
    targetPort: 7446
